// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxkjgqpmafkjwpxfmera.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4a2pncXBtYWZrandweGZtZXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzE4NTUsImV4cCI6MjA3MjkwNzg1NX0.XOBK39Z4I3r483HztyWMidi__NnqNbZ4NzBpgl7A1Fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});